### PR TITLE
Added verify endpoint, clean code structure, added socket.io

### LINKED ISSUE #4: Support proof verification
It will be helpful to have an easy way to request and verify a proof.

- [x] Create a `/verify` endpoint
- [x] Create a `Login` button that opens the Verida SSO modal allowing the user to sign in. [See SSO documentation](https://developers.verida.network/docs/tutorial/SSO)
- [x] Once logged in, show a `Request credential` button that generates an inbox request for the user to share a credential (similar to missions)
- [x] Once the credential is received, verify the proof contained within the credential. Verify the proof using either the zkpass and reclaim protocol SDK, depending on the type of proof
- [x] Display a message saying if the proof was successfully verified or not

### PR DESCRIPTION
**Pull request by icetrust0212**
closes #4

### CODE REVIEW

**Comment by icetrust0212** [comment]
#4

**Comment by tahpot** [comment]
When adding a credential. Click one of the credentials and the `Add credential` modal is still visible, it should be hidden.

Screenshot 2024-04-30 at 10 20 31 am

**Comment by tahpot** [comment]
Reclaim badge icon is transparent which makes it look a bit weird. Perhaps have both zkpass and reclaim icons in a round circle? Check the designs in Figma.

Screenshot 2024-04-30 at 10 21 30 am

**Comment by tahpot** [comment]
Update README.md with instructions on how the verify functionality works.

**Comment by tahpot** [comment]
In the `/verify` endpoint, make the `Connect` and `Request credential` appear as actual buttons.

**Comment by tahpot** [comment]
I attempted to verify a credential proof for zkpass / uber and received this error.

Screenshot 2024-04-30 at 10 48 24 am

**Comment by tahpot** [comment]
In `/verify` I requested a credential, but it is always invalid.

I also had a few errors that happened when I connected / disconnected, that then went away after a refresh. Can you just go through the whole process a few times, logging in and logging out, to make sure there's no edge case issues?

**Review by tahpot — APPROVED** [review]
Approved, however just double check the verification.

I completed it, but it the "Verified" popup appeared twice, it seems like the verification occurred twice based on my browser console.log

**Comment by tahpot** [comment]
Also, if you start the process for one connector but then close the window, then go back to the menu, choose another connector, it defaults to saying Something went wrong.

Screenshot 2024-05-01 at 1 44 07 pm

**Pull request merged**
